import React from 'react';
import { BookOpen, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const Terms: React.FC = () => {
    const navigate = useNavigate();

    return (
        <main style={{ flex: 1, padding: '3rem', marginLeft: '280px', minHeight: '100vh', background: 'var(--bg-main)' }}>
            <button 
                onClick={() => navigate(-1)}
                style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', background: 'white', border: '1px solid #eee', padding: '0.75rem 1.25rem', borderRadius: '12px', cursor: 'pointer', marginBottom: '2rem', fontWeight: 600 }}
            >
                <ArrowLeft size={18} /> Back
            </button>

            <header style={{ marginBottom: '3rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1rem' }}>
                    <BookOpen size={32} color="var(--primary)" />
                    <h1 style={{ fontSize: '2.5rem', color: 'var(--text-main)', fontWeight: 800 }}>Terms of Service</h1>
                </div>
                <p style={{ color: 'var(--text-muted)', fontSize: '1.1rem' }}>Last updated: April 7, 2026</p>
            </header>

            <div className="glass" style={{ padding: '3rem', borderRadius: '32px', maxWidth: '900px', lineHeight: 1.8, color: 'var(--text-main)' }}>
                <section style={{ marginBottom: '2rem' }}>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: 800, marginBottom: '1rem' }}>1. Acceptance of Terms</h2>
                    <p>By accessing and using GrowSmart, you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
                </section>

                <section style={{ marginBottom: '2rem' }}>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: 800, marginBottom: '1rem' }}>2. Use of Service</h2>
                    <p>GrowSmart is an agricultural intelligence platform provided for personal and educational use. You agree to use the Service in accordance with all applicable local, state, and national laws.</p>
                </section>

                <section style={{ marginBottom: '2rem' }}>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: 800, marginBottom: '1rem' }}>3. User Conduct</h2>
                    <p>Users are responsible for the content they upload (e.g., land photos). You agree not to upload any content that is illegal, harmful, or infringes on the rights of others.</p>
                </section>

                <section style={{ marginBottom: '2rem' }}>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: 800, marginBottom: '1rem' }}>4. AI and Accuracy Disclaimer</h2>
                    <p>The Service provides agricultural insights generated by artificial intelligence. While we aim for high accuracy, the results should NOT be considered professional agronomic or horticultural advice. GrowSmart is not liable for any losses incurred from reliance on AI-generated data.</p>
                </section>

                <section style={{ marginBottom: '2rem' }}>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: 800, marginBottom: '1rem' }}>5. Limitation of Liability</h2>
                    <p>In no event shall GrowSmart or its affiliates be liable for any indirect, incidental, or consequential damages resulting from the use or inability to use the Service.</p>
                </section>

                <section>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: 800, marginBottom: '1rem' }}>6. Changes to Terms</h2>
                    <p>GrowSmart reserves the right to modify these terms at any time. Your continued use of the Service after any such changes constitutes your acceptance of the new terms.</p>
                </section>
            </div>
        </main>
    );
};

export default Terms;
